[package]
name = "c-rust-interop"
version = "0.1.0"
authors = ["Lucas Alison de Lima <lucasalison.lima926@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "double_input"
crate-type = ["staticlib"]
