[package]
name = "option-example"
version = "0.1.0"
authors = ["Lucas Alison de Lima <lucas.alison@orsegups.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
