[package]
name = "aws-s3-rust-rusoto"
version = "0.1.0"
authors = ["Lucas Alison de Lima <lucasalison.lima926@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = "0.40.0"
rusoto_s3 = "0.40.0"